update config to use 2.0v of plugin
dnwarnock/sample.async.websockets pull request #1
Opened 2017-05-31 19:51 UTC by dnwarnock

2017-05-31 21:03 UTC, cthigh commented
At some point this project could be built with Gradle or Maven, but the build.gradle file was removed about a year ago. The documentation, https://github.com/dnwarnock/sample.async.websockets/blob/master/docs/Using-cmd-line.md, still talks about building with Gradle. We should update the doc.

2017-05-31 21:08 UTC, cthigh commented on async-websocket-wlpcfg/pom.xml
> +                    	<war.name>${warName}-${warVersion}</war.name>
How is this `war.name` property used?  Before we added `<stripVersion>true</stripVersion>`, the war name had the version but we took it off to match what was configured in server.xml file.

2017-05-31 21:21 UTC, cthigh commented on async-websocket-wlpcfg/pom.xml
> +                    <install/>
Don't forget you were going to add a `version` parameter to this.  Did that work?

2017-05-31 21:45 UTC, cthigh commented
Also, remember we saw that the help said to download liberty which didn't make sense.  We can fix that and close https://github.com/WASdev/sample.async.websockets/issues/27.

2017-05-31 21:47 UTC, cthigh requested changes
See my various comments on the files changed and more general comments.

2017-06-01 00:41 UTC, dnwarnock commented on async-websocket-wlpcfg/pom.xml
> +                    <install/>
Worked fine!

2017-06-01 00:50 UTC, dnwarnock commented
Should I just remove the details about gradle and downloading liberty then?

2017-06-01 04:32 UTC, patricktiu commented
I was hoping we can merge this multi-module project into a single war project. See the PR for sample.async.servletnio, https://github.com/josephca/sample.async.servletnio/pull/1.

2017-06-01 15:19 UTC, dnwarnock commented
@patricktiu our thoughts were that this sample could act as an example of using multiple modules to construct a project

2017-06-01 16:35 UTC, cthigh commented
Downloading info should be removed.  I wish we knew why they removed the gradle build.  Maybe the project was converted to a multi-module project and then gradle didn't work?  @patricktiu do you not see any value for showing a multi-module project? I was thinking it was good to show for someone who wanted to work that way.

2017-06-01 22:09 UTC, cthigh commented
@patricktiu and I had a chance to talk about this sample.  We will leave this one as a multi-project. Go ahead and update the doc to remove the references to building with gradle.

2017-06-02 15:43 UTC, dnwarnock commented
@cthigh Requested doc changes have been made

2017-06-05 17:29 UTC, cthigh approved these changes

2017-06-05 17:32 UTC, merged